
import com.mysql.jdbc.Connection;
import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import com.sun.xml.internal.bind.v2.runtime.output.SAXOutput;
import java.applet.AudioClip;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import static jdk.nashorn.internal.objects.NativeDate.getTime;
import static org.apache.poi.hssf.usermodel.HeaderFooter.date;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jona
 */
public class AgregarPaciente extends javax.swing.JFrame {

      UsuarioYClaveBD usuarioyclavebd = new UsuarioYClaveBD();
     
                                          //si no fuera static se pondria la palabra verde usuarioyclavebd
     public static final  String URL = UsuarioYClaveBD.getURL();
      public static final  String USERNAME = UsuarioYClaveBD.getUSERNAME();//usuario de la abse de datos
       public static final  String PASSWORD = UsuarioYClaveBD.getPASSWORD(); //clave de la abse de datos
       
       PreparedStatement ps;
       ResultSet rs; //variables para poder conectar a la BD
         
    public AgregarPaciente() {
         initComponents();

        
        
      //  Password.requestFocus();//esto es para que se puede volver a escribir en el Jtext si tener que clickearlo
        try {//ESTO TIENE QUE VER CON LA CLASE FONDOSQING PARA COLOCAR IMAGEN DE FONDO
            FondoSwing fondo = new FondoSwing(ImageIO.read(new File("BD/Agregar-paciente.jpg")));

            JPanel panel = (JPanel) this.getContentPane();
            panel.setBorder(fondo);
        } catch (IOException ex) {
           
        }

        diseño_Botones();
 int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
       int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().height;
    
      this.setBounds((ancho / 2) - (this.getWidth() / 2), (alto / 2) - (this.getHeight() / 2), 650, 850); //Al dividir el «ancho» entre 2 estoy ubicándome en el centro de la pantalla (horizontalmente). Pero, esto haría que el lado izquierdo de nuestra ventana colinde con el centro, así que le restamos la mitad del tamaño que tenga nuestra ventana. Esto hará que horizontalmente se coloque la ventana en el centro. Lo mismo se aplica para las coordenadas verticales.
 //modifico el ancho y alto por defecto

         this.setResizable(false); //para que no modifiquen el ancho y no se agrande
        this.setLocationRelativeTo(this); // para que este en el centro de la pantalla
        //this.setTitle("xd");
       
        
       
        
    Image icono = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/Lain.png"));//le coloco el icono a la aplicacion

        this.setIconImage(icono);

      //  this.setExtendedState(this.MAXIMIZED_BOTH); // para que inicie ocupando toda la pantalla
        TextoNombre.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TextoNombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ComboBoxNacionalidad = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        TextoDocumento = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TextoCelular = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ComboBoxGenero = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        TextoCorreo = new javax.swing.JTextField();
        BotonOK = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        ComboBoxEstado = new javax.swing.JComboBox<>();
        BotonAtras = new javax.swing.JButton();
        BotonInicio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(650, 850));

        jDateChooser1.setBackground(new java.awt.Color(0, 0, 0));
        jDateChooser1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        jDateChooser1.setMaxSelectableDate(new java.util.Date(946706506000L));
        jDateChooser1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jDateChooser1KeyTyped(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("MV Boli", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nacionalidad:");

        jLabel2.setFont(new java.awt.Font("MV Boli", 1, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Año de nacido:");

        TextoNombre.setFont(new java.awt.Font("Tempus Sans ITC", 3, 30)); // NOI18N
        TextoNombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextoNombre.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        TextoNombre.setSelectionColor(new java.awt.Color(0, 0, 0));
        TextoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoNombreActionPerformed(evt);
            }
        });
        TextoNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextoNombreKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("MV Boli", 1, 28)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre completo:");

        ComboBoxNacionalidad.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        ComboBoxNacionalidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Afganistán: Kabul.", "Albania: Tirana.", "Alemania: Berlín.", "Andorra: Andorra la Vieja.", "Angola: Luanda.", "Antigua y Barbuda: Saint John's.", "Arabia Saudita: Riad.", "Argelia: Argel.", "Argentina: Buenos Aires.", "Armenia: Ereván.", "Australia: Camberra.", "Austria: Viena.", "Azerbaiyán: Bakú.", "Bahamas: Nasáu.", "Bangladés: Daca.", "Barbados: Bridgetown.", "Baréin: Manama.", "Bélgica: Bruselas.", "Belice: Belmopán.", "Benín: Porto Novo y Cotonú.", "Bielorrusia: Minsk.", "Birmania: Naipyidó.", "Bolivia: Sucre. (*)", "Bosnia y Herzegovina: Sarajevo.", "Botsuana: Gaborone.", "Brasil: Brasilia.", "Brunéi: Bandar Seri Begawan.", "Bulgaria: Sofía.", "Burkina Faso: Uagadugú.", "Burundi: Gitega.", "Bután: Timbu.", "Cabo Verde: Praia.", "Camboya: Nom Pen.", "Camerún: Yaundé.", "Canadá: Ottawa.", "Catar: Doha.", "Chad: Yamena.", "Chile: Santiago de Chile.", "China: Pekín.", "Chipre: Nicosia.", "Ciudad del Vaticano: Ciudad del Vaticano.", "Colombia: Bogotá.", "Comoras: Moroni.", "Corea del Norte: Pionyang.", "Corea del Sur: Seúl.", "Costa de Marfil: Yamusukro.", "Costa Rica: San José.", "Croacia: Zagreb.", "Cuba: La Habana.", "Dinamarca: Copenhague.", "Dominica: Roseau.", "Ecuador: Quito.", "Egipto: El Cairo.", "El Salvador: San Salvador.", "Emiratos Árabes Unidos: Abu Dabi.", "Eritrea: Asmara.", "Eslovaquia: Bratislava.", "Eslovenia: Liubliana.", "España: Madrid.", "Estados Unidos: Washington D. C.", "Estonia: Tallin.", "Etiopía: Adís Abeba.", "Filipinas: Manila.", "Finlandia: Helsinki.", "Fiyi: Suva.", "Francia: París.", "Gabón: Libreville.", "Gambia: Banjul.", "Georgia: Tiflis.", "Ghana: Acra.", "Granada: Saint George.", "Grecia: Atenas.", "Guatemala: Ciudad de Guatemala.", "Guyana: Georgetown.", "Guinea: Conakri.", "Guinea-Bisáu: Bisáu.", "Guinea Ecuatorial: Malabo.", "Haití: Puerto Príncipe.", "Honduras: Tegucigalpa.", "Hungría: Budapest.", "India: Nueva Delhi.", "Indonesia: Yakarta.", "Irak: Bagdad.", "Irán: Teherán.", "Irlanda: Dublín.", "Islandia: Reikiavik.", "Islas Marshall: Majuro.", "Islas Salomón: Honiara.", "Israel: Jerusalén.", "Italia: Roma.", "Jamaica: Kingston.", "Japón: Tokio.", "Jordania: Amán.", "Kazajistán: Astaná.", "Kenia: Nairobi.", "Kirguistán: Biskek.", "Kiribati: Tarawa.", "Kuwait: Kuwait.", "Laos: Vientián.", "Lesoto: Maseru.", "Letonia: Riga.", "Líbano: Beirut.", "Liberia: Monrovia.", "Libia: Trípoli.", "Liechtenstein: Vaduz.", "Lituania: Vilna.", "Luxemburgo: Luxemburgo.", "Macedonia del Norte: Skopie.", "Madagascar: Antananarivo.", "Malasia: Kuala Lumpur.", "Malaui: Lilongüe.", "Maldivas: Malé.", "Malí: Bamako.", "Malta: La Valeta.", "Marruecos: Rabat.", "Mauricio: Port-Louis.", "Mauritania: Nuakchot.", "México: Ciudad de México. (*)", "Micronesia: Palikir.", "Moldavia: Chisináu.", "Mónaco: Mónaco.", "Mongolia: Ulán Bator.", "Montenegro: Podgorica.", "Mozambique: Maputo.", "Namibia: Windhoek.", "Nauru: Yaren.", "Nepal: Katmandú.", "Nicaragua: Managua.", "Níger: Niamey.", "Nigeria: Abuya.", "Noruega: Oslo.", "Nueva Zelanda: Wellington.", "Omán: Mascate.", "Países Bajos: Ámsterdam. (*)", "Pakistán: Islamabad.", "Palaos: Melekeok.", "Panamá: Panamá.", "Papúa Nueva Guinea: Port Moresby.", "Paraguay: Asunción.", "Perú: Lima.", "Polonia: Varsovia.", "Portugal: Lisboa.", "Reino Unido de Gran Bretaña e Irlanda del Norte: Londres. (*)", "República Centroafricana: Bangui.", "República Checa: Praga.", "República del Congo: Brazzaville.", "República Democrática del Congo: Kinsasa.", "República Dominicana: Santo Domingo.", "República Sudafricana: Bloemfontein, Ciudad Del Cabo y Pretoria. (*)", "Ruanda: Kigali.", "Rumanía: Bucarest.", "Rusia: Moscú.", "Samoa: Apia.", "San Cristóbal y Nieves: Basseterre.", "San Marino: San Marino.", "San Vicente y las Granadinas: Kingstown.", "Santa Lucía: Castries.", "Santo Tomé y Príncipe: Santo Tomé.", "Senegal: Dakar.", "Serbia: Belgrado.", "Seychelles: Victoria.", "Sierra Leona: Freetown.", "Singapur: Singapur.", "Siria: Damasco.", "Somalia: Mogadiscio.", "Sri Lanka: Sri Jayewardenepura (capital administrativa) y Colombo (capital comercial). (*)", "Suazilandia: Babane y Lobamba.", "Sudán: Jartum.", "Sudán del Sur: Yuba.", "Suecia: Estocolmo.", "Suiza: Berna.", "Surinam: Paramaribo.", "Tailandia: Bangkok.", "Tanzania: Dodoma.", "Tayikistán: Dusambé.", "Timor Oriental: Dili.", "Togo: Lomé.", "Tonga: Nukualofa.", "Trinidad y Tobago: Puerto España.", "Túnez: Túnez.", "Turkmenistán: Asjabad.", "Turquía: Ankara.", "Tuvalu: Fongafale.", "Ucrania: Kiev.", "Uganda: Kampala.", "Uruguay: Montevideo.", "Uzbekistán: Taskent.", "Vanuatu: Port Vila.", "Venezuela: Caracas.", "Vietnam: Hanói.", "Yemen: Saná.", "Yibuti: Yibuti.", "Zambia: Lusaka.", "Zimbabue: Harare." }));

        jLabel4.setFont(new java.awt.Font("MV Boli", 1, 28)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Documento:");

        TextoDocumento.setFont(new java.awt.Font("Tempus Sans ITC", 3, 30)); // NOI18N
        TextoDocumento.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextoDocumento.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        TextoDocumento.setSelectionColor(new java.awt.Color(0, 0, 0));
        TextoDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoDocumentoActionPerformed(evt);
            }
        });
        TextoDocumento.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextoDocumentoKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("MV Boli", 1, 28)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Correo de un familiar:");

        TextoCelular.setFont(new java.awt.Font("Tempus Sans ITC", 3, 30)); // NOI18N
        TextoCelular.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextoCelular.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        TextoCelular.setSelectionColor(new java.awt.Color(0, 0, 0));
        TextoCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoCelularActionPerformed(evt);
            }
        });
        TextoCelular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TextoCelularKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("MV Boli", 1, 28)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Celular:");

        ComboBoxGenero.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        ComboBoxGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hombre", "Mujer" }));

        jLabel7.setFont(new java.awt.Font("MV Boli", 1, 28)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Genero:");

        TextoCorreo.setFont(new java.awt.Font("Tempus Sans ITC", 3, 30)); // NOI18N
        TextoCorreo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TextoCorreo.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        TextoCorreo.setSelectionColor(new java.awt.Color(0, 0, 0));
        TextoCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoCorreoActionPerformed(evt);
            }
        });

        BotonOK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ok.png"))); // NOI18N
        BotonOK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonOK.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ok2.png"))); // NOI18N
        BotonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonOKActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("MV Boli", 1, 28)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Estado de enfermedad:");

        ComboBoxEstado.setFont(new java.awt.Font("Tempus Sans ITC", 1, 18)); // NOI18N
        ComboBoxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Urgencia menor", "Urgencia", "Emergencia", "Resucitacion" }));

        BotonAtras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Atras.png"))); // NOI18N
        BotonAtras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonAtras.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Atras2.png"))); // NOI18N
        BotonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAtrasActionPerformed(evt);
            }
        });

        BotonInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inicio.png"))); // NOI18N
        BotonInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotonInicio.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/inicio2.png"))); // NOI18N
        BotonInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonInicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 34, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ComboBoxNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ComboBoxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ComboBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextoCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BotonAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(168, 168, 168)
                                .addComponent(BotonOK, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextoCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(BotonInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(BotonInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 228, Short.MAX_VALUE)
                        .addComponent(TextoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(ComboBoxNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextoDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextoCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextoCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotonAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonOK, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoNombreActionPerformed

    }//GEN-LAST:event_TextoNombreActionPerformed

    private void TextoDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoDocumentoActionPerformed

    private void TextoCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoCelularActionPerformed

    private void TextoCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoCorreoActionPerformed

    private void TextoNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextoNombreKeyTyped
          //todo esto es para validar solo letras
        char C= evt.getKeyChar();
     
     if(Character.isDigit(C))
     {
        // getToolkit().beep(); //esto lo que ahce es hacer un sonido de beep
         evt.consume();
               
          AudioClip  sonido = java.applet.Applet.newAudioClip(getClass().getResource("/Sonidos/Advertencia.wav"));
            sonido.play();
          Icon icon = new ImageIcon(getClass().getResource("/Imagenes/AB.png")); //para poner icono al aviso
             JOptionPane.showMessageDialog(null, "<html><b><span style=\"font-size:1.3em\">Solo caracteres alfabeticos</b>", "Error✘", JOptionPane.INFORMATION_MESSAGE, icon);
         TextoNombre.setCursor(null);
     }
      else if((int)evt.getKeyChar()>32 && (int)evt.getKeyChar()<=47
             ||(int)evt.getKeyChar()>=58 && (int)evt.getKeyChar()<=64
             || (int)evt.getKeyChar()>=91 && (int)evt.getKeyChar()<=96
             || (int)evt.getKeyChar()>=123 && (int)evt.getKeyChar()<=255)
    {
       //  getToolkit().beep();//esto lo que ahce es hacer un sonido de beep
         evt.consume();
         
              
          AudioClip  sonido = java.applet.Applet.newAudioClip(getClass().getResource("/Sonidos/Advertencia.wav"));
            sonido.play();
          Icon icon = new ImageIcon(getClass().getResource("/Imagenes/AB.png")); //para poner icono al aviso
             JOptionPane.showMessageDialog(null, "<html><b><span style=\"font-size:1.3em\">Solo caracteres alfabeticos</b>", "Error✘", JOptionPane.INFORMATION_MESSAGE, icon);
         TextoNombre.setCursor(null);
     }
    }//GEN-LAST:event_TextoNombreKeyTyped

    private void TextoDocumentoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextoDocumentoKeyTyped
         //esto para valdiar solo numeros
        char C= evt.getKeyChar();
     
     if(Character.isLetter(C))
     {
        // getToolkit().beep();  //esto lo que ahce es hacer un sonido de beep
         evt.consume();
          AudioClip  sonido = java.applet.Applet.newAudioClip(getClass().getResource("/Sonidos/Advertencia.wav"));
            sonido.play();
          Icon icon = new ImageIcon(getClass().getResource("/Imagenes/123.png")); //para poner icono al aviso
             JOptionPane.showMessageDialog(null, "<html><b><span style=\"font-size:1.3em\">Solo caracteres numericos</b>", "Error✘", JOptionPane.INFORMATION_MESSAGE, icon);
         TextoDocumento.setCursor(null);
     }
     else if((int)evt.getKeyChar()>32 && (int)evt.getKeyChar()<=47
             ||(int)evt.getKeyChar()>=58 && (int)evt.getKeyChar()<=64
             || (int)evt.getKeyChar()>=91 && (int)evt.getKeyChar()<=96
             || (int)evt.getKeyChar()>=123 && (int)evt.getKeyChar()<=255)
    {
       //  getToolkit().beep();// //esto lo que ahce es hacer un sonido de beep
         evt.consume();
          AudioClip  sonido = java.applet.Applet.newAudioClip(getClass().getResource("/Sonidos/Advertencia.wav"));
            sonido.play();
          Icon icon = new ImageIcon(getClass().getResource("/Imagenes/123.png")); //para poner icono al aviso
             JOptionPane.showMessageDialog(null, "<html><b><span style=\"font-size:1.3em\">Solo caracteres numericos</b>", "Error✘", JOptionPane.INFORMATION_MESSAGE, icon);
         TextoDocumento.setCursor(null);
     }
    }//GEN-LAST:event_TextoDocumentoKeyTyped

    private void TextoCelularKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TextoCelularKeyTyped
          //esto para valdiar solo numeros
        char C= evt.getKeyChar();
     
     if(Character.isLetter(C))
     {
        // getToolkit().beep();  //esto lo que ahce es hacer un sonido de beep
         evt.consume();
          AudioClip  sonido = java.applet.Applet.newAudioClip(getClass().getResource("/Sonidos/Advertencia.wav"));
            sonido.play();
          Icon icon = new ImageIcon(getClass().getResource("/Imagenes/123.png")); //para poner icono al aviso
             JOptionPane.showMessageDialog(null, "<html><b><span style=\"font-size:1.3em\">Solo caracteres numericos</b>", "Error✘", JOptionPane.INFORMATION_MESSAGE, icon);
         TextoDocumento.setCursor(null);
     }
    }//GEN-LAST:event_TextoCelularKeyTyped

    private void BotonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonOKActionPerformed
 boolean validacion_Correo=false; //valido si el correo tiene @ o termina en com oco o sus derivados
//AQUI ABAJO VALIDARE SI LA FECHA INGRESADA NO ES MAYOR  A LA ACTUAL Y TAMBN ESTA EL PROCESO DE CONVERTIR LA FECHA EN FORMATO NORMAL
 boolean validacion_Fecha =true;
Date FechaActual = new Date(System.currentTimeMillis());//me da la fecha actual
Date FechaIngresadaDate = jDateChooser1.getDate(); //cojo la fecha que ingresa el usuario  
         String Fechaingresada = new SimpleDateFormat("dd-MM-yyyy").format(FechaIngresadaDate);//LA CONVIERTO A FORMATO NORMAL
          SimpleDateFormat date = new SimpleDateFormat("dd-MM-yyyy");
          try { 
              Date fechaInicioDate = date.parse(Fechaingresada);
              if(fechaInicioDate.after(FechaActual)){//si fecha ingresada es mayor a la actual...
   validacion_Fecha=false;
}else{//si no pues lo contrario y no pasa nada
    
}
          } catch (ParseException ex) {
           
          }
          
       
 
        if(jDateChooser1.getDate()==null || validacion_Fecha==false){
    AudioClip  sonido = java.applet.Applet.newAudioClip(getClass().getResource("/Sonidos/Advertencia.wav"));
            sonido.play();
    JOptionPane.showMessageDialog(null, "<html><b><span style=\"font-size:1.3em\">El campo fecha esta vacio o mal escrito</b>", "Error✘", JOptionPane.INFORMATION_MESSAGE);
  jDateChooser1.requestFocus();
  return;
        }    
        else if ("".equals(TextoCorreo.getText())){//si el correo esta vacio no pasa nada asi q paso al metodo
        
        agregarPaciente();
        return;//pa q cuando termine se salga 
        }
else if (TextoCorreo.getText().contains("@")&& TextoCorreo.getText().endsWith(".com") ||TextoCorreo.getText().endsWith(".co")||TextoCorreo.getText().endsWith(".org")  ||TextoCorreo.getText().endsWith(".es") ||TextoCorreo.getText().endsWith(".it") ||TextoCorreo.getText().endsWith(".fr") ||TextoCorreo.getText().endsWith(".cat") ||TextoCorreo.getText().endsWith(".net"))  {
         validacion_Correo=true;
         
        }
        
 if(validacion_Correo==false || TextoCorreo.getText().startsWith("@") ){
             AudioClip  sonido;
       sonido= java.applet.Applet.newAudioClip(getClass().getResource("/Sonidos/Error.wav"));
        sonido.play();
           Icon icon = new ImageIcon(getClass().getResource("/Imagenes/Correo invalido.png")); //para poner icono al aviso
            JOptionPane.showMessageDialog(null, "<html><b><span style=\"font-size:1.3em\">Correo invalido</b>", " Error✘", JOptionPane.INFORMATION_MESSAGE, icon);
      TextoCorreo.requestFocus();//esto es para que se puede volver a escribir en el Jtext si tener que clickearlo
        }
else{

 agregarPaciente();
}
    }//GEN-LAST:event_BotonOKActionPerformed

    public void agregarPaciente(){
        String Mes="";
        String Dia ="";
        String Año ="";
      try {//aqui entra a la BD y lo agrega
          long IDpaciente =0;
          if(TextoDocumento.getText().equals("")){//si esta vacio , le asigno un ID aleatorio
           int a =(int) (Math.random() * 9);
        int b = (int) (Math.random() * 9);
        int c = (int) (Math.random() * 9);//para generar el codigo de barras
        int d =(int) (Math.random() * 9);
        int e = (int) (Math.random() * 9);
int f =(int) (Math.random() * 9);
IDpaciente=a+b+c+d+e+f;
          }
          else{//si no esta vacio se lo asigno
          IDpaciente= Long.parseLong(TextoDocumento.getText());
          
          }
          Connection con =null;
        con =  getConection();
        ps = con.prepareStatement("INSERT INTO paciente (IDPaciente, Nombre, FechaNacimiento, Nacionalidad, EstadoEnfermedad, Genero, Correo, Celular) VALUES(?,?,?,?,?,?,?,?)");
        ps.setLong(1, IDpaciente);//para almacenar en la BD, el 1 es su posicion en la tabla
          ps.setString (2,TextoNombre.getText());
          
       
String FechaConHora = jDateChooser1.getDate().toString();//convierto la fecha a string
          for (int i = 0; i < FechaConHora.length(); i++) {//recorrere toda la palabra de deracha a izq
                Mes = FechaConHora.substring(0, FechaConHora.length() - i);//desde atras recorrere todo hasta detectar cuando hay un espacio
                if(Mes.length()>8){//si sus caracteres son mayores a 8 siga el ciclo           
          
                   
                }
                else{//si no es por q ya queda el dia y mes
                   Mes= FechaConHora.substring(0, FechaConHora.length() - i);//se lo asigno
                    break;//rompo el ciclo
                }
            }
          
          Mes = Mes.substring(4,7);//aqui elimino el dia y obtengo solo el mes - letras q  elimina por la izq , letras que deja
         Dia= jDateChooser1.getDate().toString();//ahora hallare el dia
          Dia = Dia.substring(8,10);//aqui cojo el dia , letras q elimino a la izq , letras q dejo
            Año= jDateChooser1.getDate().toString();
               Año = Año.substring(24,28);
         
          ps.setString (3, Dia+"-"+Mes+"-"+Año);//
          ps.setString (4, (String) ComboBoxNacionalidad.getSelectedItem());//posicon 4 de la BD nacionalidad
           ps.setString (5, (String) ComboBoxEstado.getSelectedItem());
                     ps.setString (6, (String) ComboBoxGenero.getSelectedItem());
                      ps.setString (7,  TextoCorreo.getText());  
                               ps.setString (8,  TextoCelular.getText());

        int res=  ps.executeUpdate();
        
        if(res>0){//si se guardo ira aqui
             AudioClip  sonido = java.applet.Applet.newAudioClip(getClass().getResource("/Sonidos/Realizado.wav"));
            sonido.play();
          Icon icon = new ImageIcon(getClass().getResource("/Imagenes/chulito.png")); //para poner icono al aviso
             JOptionPane.showMessageDialog(null, "<html><b><span style=\"font-size:1.3em\">Guardado</b>", "OK✔", JOptionPane.INFORMATION_MESSAGE, icon);
        }
        else{//si no se guardo aqui
                    AudioClip  sonido = java.applet.Applet.newAudioClip(getClass().getResource("/Sonidos/Error.wav"));
            sonido.play();
          Icon icon = new ImageIcon(getClass().getResource("/Imagenes/X.png")); //para poner icono al aviso
             JOptionPane.showMessageDialog(null, "<html><b><span style=\"font-size:1.3em\">No se pudo guardar, vuelve a intentarlo</b>", "Error✘", JOptionPane.INFORMATION_MESSAGE, icon);
        }
        con.close();
    } catch (Exception e) {
        AudioClip    sonido = java.applet.Applet.newAudioClip(getClass().getResource("/Sonidos/Error.wav"));
            sonido.play();
            Icon icon = new ImageIcon(getClass().getResource("/Imagenes/X.png")); //para poner icono al aviso
             JOptionPane.showMessageDialog(null, "<html><b><span style=\"font-size:1.3em\">Error desconocido</b>", "Error✘", JOptionPane.INFORMATION_MESSAGE, icon);
    }
    }
    
    private void jDateChooser1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jDateChooser1KeyTyped
       
    }//GEN-LAST:event_jDateChooser1KeyTyped

    private void BotonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAtrasActionPerformed

if("LAIN☢".equals(this.getTitle())){
    Menu menu = new Menu();//lo dirijo al loginadmin
        menu.setTitle("LAIN☢");//para que muestre en el la pantalla esquina superior izquierda un titutlo
        menu.setVisible(true);
        AudioClip sonido2 = java.applet.Applet.newAudioClip(getClass().getResource("/Sonidos/Boton.wav"));
        sonido2.play();
          Menu.BotonAdmin.setVisible(false);//en el menu puse esta variable publica la llamo y la modifico
        dispose();//para cerrar la ventana actual
}
else {
  Menu menu = new Menu();//lo dirijo al loginadmin
        menu.setTitle("LAIN☢-Admin");//para que muestre en el la pantalla esquina superior izquierda un titutlo
        menu.setVisible(true);
        AudioClip sonido2 = java.applet.Applet.newAudioClip(getClass().getResource("/Sonidos/Boton.wav"));
        sonido2.play();
          Menu.BotonAdmin.setVisible(true);//en el menu puse esta variable publica la llamo y la modifico
        dispose();//para cerrar la ventana actual

}

       
    }//GEN-LAST:event_BotonAtrasActionPerformed

    private void BotonInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonInicioActionPerformed
        Login login = new Login();//lo dirijo al loginadmin
        login.setTitle("LAIN☢");//para que muestre en el la pantalla esquina superior izquierda un titutlo
        login.setVisible(true);
        AudioClip sonido2 = java.applet.Applet.newAudioClip(getClass().getResource("/Sonidos/Boton.wav"));
        sonido2.play();
        dispose();//para cerrar la ventana actual
    }//GEN-LAST:event_BotonInicioActionPerformed

    
     public static  Connection getConection(){
   
       Connection con = null;
       
       try {
           Class.forName("com.mysql.jdbc.Driver");
         con=  (Connection) DriverManager.getConnection(URL,USERNAME, PASSWORD);
          
       } catch (Exception e) {
           System.out.println(e);
       }
       return con;
   }
    
    public void diseño_Botones(){
         
         jDateChooser1.setOpaque(false);
         
         //esto para evitar que el usuario ingrese una fecha futuro
          Date myDate = new Date();

         jDateChooser1.setMaxSelectableDate(myDate);
       
        BotonOK.setOpaque(false);
        BotonOK.setContentAreaFilled(false);
        BotonOK.setBorderPainted(false);
    
        
         BotonAtras.setOpaque(false);
        BotonAtras.setContentAreaFilled(false);
        BotonAtras.setBorderPainted(false);
        
          BotonInicio.setOpaque(false);
        BotonInicio.setContentAreaFilled(false);
        BotonInicio.setBorderPainted(false);
    
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAtras;
    private javax.swing.JButton BotonInicio;
    private javax.swing.JButton BotonOK;
    private javax.swing.JComboBox<String> ComboBoxEstado;
    private javax.swing.JComboBox<String> ComboBoxGenero;
    private javax.swing.JComboBox<String> ComboBoxNacionalidad;
    private javax.swing.JTextField TextoCelular;
    private javax.swing.JTextField TextoCorreo;
    private javax.swing.JTextField TextoDocumento;
    private javax.swing.JTextField TextoNombre;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
